language: csharp
solution: ObjectDisposedFodyAddin.sln
install:
  - nuget restore ObjectDisposedFodyAddin.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - dotnet build -c Release
  - dotnet test -c Release ./src/Tests
